language: go
install:
  - go get -v github.com/sfp13/hugo
script:
  - hugo version
  - make build
branches:
  only:
    - master

# env:
#   global:
#     - 'SFTP_USER=sftpuser'
#     - 'SFTP_PASSWORD=st@tic$ftpu$3r'
#     - 'SFTP_KEY=[base64-encoded-rsa-key]'
# after_success:
#   - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
#   - curl --ftp-create-dirs
#         -T filename
#         --key /tmp/sftp_rsa
#         sftp://${SFTP_USER}:${SFTP_PASSWORD}@example.com/directory/filename
