baseURL = "https://static.grinnell.edu/"
title = "static.Grinnell.edu"
# publishDir = "docs"
languageCode = "en-US"
theme = "bootstrap-bp-hugo-startpage"
googleAnalytics = "UA-4766052-13"
copyright = "Mark A. McFate"
enableRobotsTXT = true
pygmentsCodeFences = true
canonifyurls = true
paginate = 5

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[permalinks]
  posts = "/:year/:month/:slug/"
  post = "/:year/:month/:slug/"
  pages = "/:slug/"
  page = "/:slug/"

[Author]
  name = "Mark A. McFate"

[params]
  description = "Welcome to the static.Grinnell.edu landing page at Grinnell College!"
  #images = ["logo.jpg"]
  startPageColumns = true
  welcomeText = "This landing page is designed solely to provide navigation to the sites/services listed below.  Now hosted on GitHub Pages!"
  buildDate = '2021-10-05 17:32 CST'

[[params.searchEngines]]
  name = "Google"
  activated = true
  url = "https://www.google.com/search"
